[build]
  command = "git submodule update --init --recursive && rm -rf public/ && hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.138.0"
  HUGO_EXTENDED = "true"

[dev]
  command = "hugo server"
  publish = "public"
  port = 1314
